version: "3.9"

services:
   nextjs-app:
      build: .
      ports:
         - "3000:3000"
      volumes:
         - ./data.db:/app/data.db
      environment:
         - NODE_ENV=production
      cap_add:
         - SYS_RESOURCE
      restart: unless-stopped
