import { inter } from "@/lib/fonts"
import { cn } from "@/lib/utils"
import type { Metadata } from "next"
import "./globals.css"
import Navbar from "@/components/layout/navbar/navbar"
import LocaleProvider from "@/providers/Locale"

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang="en">
         <body
            className={cn(
               `dark text-text-primary bg-primary relative flex min-h-screen flex-col overflow-x-hidden tracking-[0.01em] antialiased`,
               inter.className,
            )}
         >
            <LocaleProvider>
               <Navbar />
               {children}
            </LocaleProvider>
         </body>
      </html>
   )
}
