import { inter } from "@/lib/fonts"
import { cn } from "@/lib/utils"
import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang="en">
         <body
            className={cn(
               `dark text-t-primary bg-primary relative flex min-h-screen flex-col overflow-x-hidden antialiased`,
               inter.className,
            )}
         >
            {children}
         </body>
      </html>
   )
}
