import Navbar from "@/components/layout/navbar/Navbar"
import { inter } from "@/lib/fonts"
import { cn } from "@/lib/utils"
import LocaleProvider from "@/providers/Locale"
import { NuqsAdapter } from "nuqs/adapters/next/app"
import type { Metadata } from "next"
import "./globals.css"
import ThemeProvider from "@/providers/Theme"
import { getServerLocale } from "@/utils/server-locale"
import Footer from "@/components/layout/Footer"

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
}

export default async function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   const locale = await getServerLocale()
   return (
      <html
         lang={locale}
         dir={locale === "ar" ? "rtl" : "ltr"}
         key={locale}
         suppressHydrationWarning
      >
         <body
            className={cn(
               `text-text-primary bg-primary relative flex min-h-screen flex-col overflow-x-hidden antialiased`,
               inter.className,
            )}
         >
            <ThemeProvider attribute="class" defaultTheme="dark">
               <LocaleProvider>
                  <NuqsAdapter>
                     <Navbar />
                     <main className="mx-auto w-[90%] flex-1 flex-grow overflow-x-hidden xl:max-w-7xl">
                        {children}
                     </main>
                     <Footer />
                  </NuqsAdapter>
               </LocaleProvider>
            </ThemeProvider>
         </body>
      </html>
   )
}
