import Footer from "@/components/layout/Footer"
import Navbar from "@/components/layout/navbar/Navbar"
import { inter } from "@/lib/fonts"
import { cn } from "@/lib/utils"
import ThemeProvider from "@/providers/Theme"
import { LocaleParams } from "@/types"
import type { Metadata } from "next"
import { NextIntlClientProvider, hasLocale } from "next-intl"
import { setRequestLocale } from "next-intl/server"
import { notFound } from "next/navigation"
import NextTopLoader from "nextjs-toploader"
import { NuqsAdapter } from "nuqs/adapters/next/app"
import { Toaster } from "sonner"
import { routing } from "../../i18n/routing"
import "./globals.css"

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
}

export default async function RootLayout({
   children,
   params,
}: {
   children: React.ReactNode
   params: LocaleParams["params"]
}) {
   const { locale } = await params
   if (!hasLocale(routing.locales, locale)) {
      notFound()
   }
   setRequestLocale(locale)

   return (
      <html
         lang={locale}
         dir={locale === "ar" ? "rtl" : "ltr"}
         key={locale}
         suppressHydrationWarning
      >
         <body
            className={cn(
               `text-text-primary bg-primary relative flex min-h-screen flex-col overflow-x-hidden antialiased`,
               inter.className,
            )}
         >
            <NextIntlClientProvider>
               <ThemeProvider
                  attribute="class"
                  defaultTheme="dark"
                  themes={["light", "dark"] as const}
               >
                  <NuqsAdapter>
                     <NextTopLoader
                        color="#fd8c73"
                        shadow={false}
                        showSpinner={false}
                        height={2}
                     />
                     <Navbar locale={locale} />

                     <main className="mx-auto w-[90%] flex-1 flex-grow overflow-x-hidden md:w-[95%] xl:max-w-[1250px]">
                        {children}
                     </main>
                     <Footer />

                     <Toaster position="bottom-right" richColors />
                  </NuqsAdapter>
               </ThemeProvider>
            </NextIntlClientProvider>
         </body>
      </html>
   )
}
